version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: llm-evals-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llm_evals
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-evals
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/llm_evals
    depends_on:
      - postgres

volumes:
  postgres_data:
