version: '3.8'
services:
  postgres:
    image: registry-jpw1.r-local.net/item-page-tools/llm_evals_database:latest
    container_name: llm-evals-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llm_evals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-evals-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@llm-evals-database-80-item-page-tools.jpw1-caas1-dev1.caas.jpw1a.r-local.net:5432/llm_evals?schema=public
    depends_on:
      - postgres

  backup:
    build:
      context: .
      dockerfile: scripts/Dockerfile.backup
    container_name: llm-eval-backup
    volumes:
      - db_backups:/backup
    depends_on:
      - postgres

volumes:
  postgres_data:
  db_backups: